### ISSUE TITLE
Enhancement: speed up the reading of chords from the device

### ISSUE THREAD

**Issue by rccarlson** [iq-eq-us/dot-io#121]
`getGet()` from `download.tsx` is adding chords read from device one by one to the site. This is extremely slow (O(N^2) speed).

Chords should be read all at one up front, then bulk copied to the UI to save time

**Comment by jdestgermain** [comment]
Duplicate of #88

**Comment by jdestgermain** [comment]
I suppose since this one has more information of the source of the problem, I will close the other issue

**Comment by jdestgermain** [comment]
Upon connecting, download all chords and then render afterwards instead of rendering as we go
