### ISSUE TITLE
Enhancement: Add a repository About description

### ISSUE THREAD

**Issue by duianto** [iq-eq-us/dot-io#157]
**Is your feature request related to a problem? Please describe.**
This repository's About description is empty (top right on the main page).
It shows the default message:
>No description, website, or topics provided.

If someone is looking for interesting repositories on GitHub, then they will probably skip over this one because the description is blank.

When searching for `dot io`, then page 3 looked like this:

![msedge_wKF7gG9Rkj](https://github.com/iq-eq-us/dot-io/assets/13420573/3cba31a2-ede4-4eb1-8772-a8a625fac461)

**Describe the solution you'd like**
Add a repository About description.
If it includes the training page link: https://www.iq-eq.io/
then it's easy to jump directly to the main page that the repository is handling.

**Comment by jdestgermain** [comment]
Added 
![image](https://github.com/iq-eq-us/dot-io/assets/11359044/014a1f29-f2f6-4ac1-aec9-97a00f9e9799)
Thanks for pointing out!
