### ISSUE TITLE
Defect: Chord output flip flops between all caps and desired output

### ISSUE THREAD

**Issue by cklint12** [iq-eq-us/dot-io#215]
**Describe the bug**
Chord output flip flops between all caps and desired output.

Chord: eghl
Desired Output: English
Actual output: ENGLISH on 1st try, English on second try, ENGLISH on 3rd try, etc.

Culprit: Capitalizing the 1st letter of the output during impulse chording. This is easily replicable with other impulse chords.

**To Reproduce**
1. Impluse chord with eghl as input
2. Type English as output 

**Expected behavior**
When you chord eghl, the output is going to go back and forth between ENGLISH and English.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - CharaChorder Device:  CC1
 - CCOS Version: CCOS 1.1.3

**Comment by jdestgermain** [comment]
Moving this to https://github.com/CharaChorder/CCOS-firmware/issues/56
