### ISSUE TITLE
New Development: Progress Bar

### ISSUE THREAD

**Issue by COChara** [iq-eq-us/dot-io#7]
Adding a progress bar would provide an easy-to-follow visual for anyone on the site going through each module.

**Description**:
Users want to track their progress while training on dot i/o this progress bar should work depending on what metric we're tracking for the respective tiers. This will give users a visual to follow when working the tiers and modules. 

**Requirements** 

**CPM Tier:**
    For each module (letters, trigrams, words, test) each increase will be based on the completion of the word. If the word has been typed equal to or more than 10 times AND the speed of the word's completion is greater than the speedGoal for that module we can increase the completion percentage. The goal number for completion for the entire data set should be equal to the number of words, letters, or trigrams that are being tested. 
    
    
**CHM Tier:** 
    For each module (English 200, All Chords and Custom) each time a word is mastered) typed a minimum of 10 times and the word was completed at an average of 100 wpm for the respective word. Once that is achieved the word can be considered 'Mastered' and we can increase the completion bar. The goal for the completion of the module should be based on the number of words per module. 

If there are any questions please @ COChara .

**Comment by zhukant** [comment]
@COChara this is not a lot of content regarding the suggestion, so I hope I understood you correctly. I would also like this feature. I think a progress bar in the practice area would be very helpful and encouraging. This should be similar to what launchpad.charachorder.com/#/training had, where one received progress advancement for a particular training module in a visual progress bar at the top when the recorded speed of distinct chords in that module surpassed the target goal. 
![launchpad_progress_bar_2023-03-17](https://user-images.githubusercontent.com/13786997/226078142-dd1a8e83-1552-4f6d-8bd8-220ba834c307.png)

According to this comment in the CharaChorder Discord Server on the dot-io channel from a user (Tangent Chang#4487) who appears to be familiar with the codebase, there is currently no such metric in the dot-io version of the training modules: https://discord.com/channels/861730583092658206/1086356304680984636/1086472525959139339

**Comment by jdestgermain** [comment]
Is this issue able to be closed now?
