### ISSUE TITLE
Development/contribution process

### ISSUE THREAD

**Issue by jdestgermain** [iq-eq-us/dot-io#8]
Can someone write into the Readme the steps to take to actually contribute to the project. It isn't clear to me what the steps would be. What are the branches/environments, etc.

Make PRs against what branch, etc?

**Comment by rileykeen** [comment]
We have reduced the branches to 'latest' & 'development' and have also updated the 'How to contribute' section in the Read Me. Does this answer your question?

**Comment by jdestgermain** [comment]
Yes, thanks!
