### ISSUE TITLE
Defect: Display issues in CC1 preview

### ISSUE THREAD

**Issue by andy23512** [iq-eq-us/dot-io#97]
From discord message https://discord.com/channels/861730583092658206/1086356304680984636/1130400848988606495

- Comma is too similar to period.
- Num shift text is a bit too close to the black circle in the middle, they blend together.
- M, K and G, W are at different heights.

**Comment by duianto** [comment]
All three points have been fixed:
fix: update CC1 device preview, larger comma, apostrophe, period #149
fix: update CC1 device preview, move numshift away from center #148
fix: update CC1 device preview, horizontally align K with M and W with G #150
